[package]
name = "summars"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bytes = "1"
log = { version = "0.4", features = ['std'] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tokio = { version = "1", features = ["fs","sync","rt-multi-thread"] }
cln-rpc = "0.1.2"
cln-plugin = "0.1.2"
tabled = "0.10"
num-format = "0.4"
struct-field-names-as-array = "0.1"
chrono = "0.4"
parking_lot = "0.12"

# [dev-dependencies]
# tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
# cln-grpc = "0.1"

[profile.release]
codegen-units = 1
lto = "fat"
# debug = true
